// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.BootstrapInfo>}
 */
export function Bootstrap() {
    return $Call.ByID(3698296714).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenInExplorer reveals a file or directory in the system file manager.
 * Directories open in-place; files are selected/revealed when the platform supports it.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenInExplorer(path) {
    return $Call.ByID(2739626308, path);
}

/**
 * SelectDirectory opens a native folder picker and returns the selected path.
 * Empty string means the user cancelled.
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(2824785567);
}

// Private type creation functions
const $$createType0 = $models.BootstrapInfo.createFrom;
