// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BootstrapInfo {
    /**
     * Creates a new BootstrapInfo instance.
     * @param {Partial<BootstrapInfo>} [$$source = {}] - The source object to create the BootstrapInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("gateway_base" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gateway_base"] = "";
        }
        if (!("websocket_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["websocket_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BootstrapInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BootstrapInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BootstrapInfo(/** @type {Partial<BootstrapInfo>} */($$parsedSource));
    }
}
